version: '3.8'
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/logs/clickhouse-server/:/var/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9363:9363"
    depends_on:
      - zk
    restart: unless-stopped
  zk:
    container_name: zk
    hostname: zk
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=MYNODEID
      - ZOO_SERVERS=0.0.0.0:2888:3888,NODE2HOST:2888:3888,NODE3HOST:2888:3888
  # vector:
  #   image: timberio/vector:0.36.1-debian
  #   volumes:
  #     - ${PWD}/config/vector/vector.yaml:/etc/vector/vector.yaml:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped
  #   command:
  #     - --config
  #     - /etc/vector/vector.yaml
