version: '3.8'
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config.d/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
      - ${PWD}/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/logs/clickhouse-server/:/var/log/clickhouse-server/
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
      - "9363:9363"
      - "9181:9181"
      - "9234:9234"
    restart: unless-stopped
