version: '3.8'
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:${CHVER:-latest}"
    user: "101:101"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/node1/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/node1/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9363:9363"
    depends_on:
      - clickhouse-keeper
  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}"
    user: "101:101"
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
     - ${PWD}/node1/keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
        - "127.0.0.1:9181:9181"
