version: '3.8'
services:
  clickhouse:
    image: "clickhouse/clickhouse-server:latest"
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/config/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/logs/clickhouse-server/:/var/log/clickhouse-server/
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9363:9363"
    depends_on:
      - clickhouse-keeper
    restart: unless-stopped
  clickhouse-keeper:
    image: "clickhouse/clickhouse-keeper:latest"
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
     - ${PWD}/config/keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
     - ${PWD}/logs/clickhouse-keeper/:/var/log/clickhouse-keeper
    ports:
        - "127.0.0.1:9181:9181"
    restart: unless-stopped
  # vector:
  #   image: timberio/vector:0.36.1-debian
  #   volumes:
  #     - ${PWD}/config/vector/vector.yaml:/etc/vector/vector.yaml:ro
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   ports:
  #     - 8686:8686
  #   restart: unless-stopped
  #   command:
  #     - --config
  #     - /etc/vector/vector.yaml
